// Generated by CoffeeScript 1.7.1
(function() {
  "use strict";
  angular.module("dcFrontendApp", ["ngCookies", "ngResource", "ngSanitize", "ngRoute"]).config(function($routeProvider) {
    $routeProvider.when("/", {
      templateUrl: "views/main.html",
      controller: "MainCtrl"
    }).otherwise({
      redirectTo: "/"
    });
  });

}).call(this);
