// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';

  /**
    * @ngdoc function
    * @name dcFrontendApp.controller:MainCtrl
    * @description
    * # MainCtrl
    * Controller of the dcFrontendApp
   */
  angular.module('dcFrontendApp').controller('MainCtrl', function($scope) {
    return $scope.awesomeThings = ['HTML5 Boilerplate', 'AngularJS', 'Karma'];
  });

}).call(this);
